import jsPDF from 'jspdf';
import type { DiagnoseCropDiseaseOutput } from '@/ai/flows/crop-disease-diagnosis';

const translations: Record<string, any> = {
  en: {
    title: 'Crop Disease Diagnosis Report',
    reportDate: 'Report Date',
    reportTime: 'Report Time',
    farmerName: 'Farmer Name',
    diseaseId: 'DISEASE IDENTIFICATION',
    diseaseName: 'Disease Name',
    severity: 'Severity Level',
    confidence: 'AI Confidence',
    modelUsed: 'Model Used',
    cause: 'Cause',
    weatherCond: 'FAVORABLE WEATHER CONDITIONS',
    symptoms: 'SYMPTOMS',
    immediateTreat: 'IMMEDIATE TREATMENT STEPS',
    organicTreat: 'ORGANIC TREATMENT OPTIONS',
    chemicalTreat: 'CHEMICAL TREATMENT & PESTICIDES',
    followUp: 'FOLLOW-UP CARE',
    preventive: 'PREVENTIVE MEASURES',
    resources: 'ADDITIONAL RESOURCES',
    footer: 'Generated by Farmingo AI | For educational purposes | Consult experts for severe cases',
    page: 'Page',
    of: 'of',
  },
  hi: {
    title: 'Fasal Rog Nidan Report',
    reportDate: 'Report Tithi',
    reportTime: 'Report Samay',
    farmerName: 'Kisan Ka Naam',
    diseaseId: 'ROG PAHCHAN',
    diseaseName: 'Rog Ka Naam',
    severity: 'Gambhirta Star',
    confidence: 'AI Vishwas',
    modelUsed: 'Model Upyog',
    cause: 'Karan',
    weatherCond: 'ANUKUL MAUSAM KI STHITI',
    symptoms: 'LAKSHAN',
    immediateTreat: 'TATKAL UPCHAR KADAM',
    organicTreat: 'JAIVIK UPCHAR VIKALP',
    chemicalTreat: 'RASAYANIK UPCHAR AUR KITNASHAK',
    followUp: 'ANUVARTI DEKHBHAL',
    preventive: 'NIVARAK UPAY',
    resources: 'ATIRIKT SANSADHAN',
    footer: 'Farmingo AI dwara utpann | Shaikshik uddeshyon ke liye',
    page: 'Prishth',
    of: 'ka',
  },
  es: {
    title: 'Informe de Diagnóstico de Enfermedades de Cultivos',
    reportDate: 'Fecha del Informe',
    reportTime: 'Hora del Informe',
    farmerName: 'Nombre del Agricultor',
    diseaseId: 'IDENTIFICACIÓN DE ENFERMEDAD',
    diseaseName: 'Nombre de la Enfermedad',
    severity: 'Nivel de Gravedad',
    confidence: 'Confianza de IA',
    modelUsed: 'Modelo Utilizado',
    cause: 'Causa',
    weatherCond: 'CONDICIONES CLIMÁTICAS FAVORABLES',
    symptoms: 'SÍNTOMAS',
    immediateTreat: 'PASOS DE TRATAMIENTO INMEDIATO',
    organicTreat: 'OPCIONES DE TRATAMIENTO ORGÁNICO',
    chemicalTreat: 'TRATAMIENTO QUÍMICO Y PESTICIDAS',
    followUp: 'CUIDADO DE SEGUIMIENTO',
    preventive: 'MEDIDAS PREVENTIVAS',
    resources: 'RECURSOS ADICIONALES',
    footer: 'Generado por Farmingo AI | Con fines educativos | Consulte a expertos para casos graves',
    page: 'Página',
    of: 'de',
  },
};

export function generateDiagnosisReport(
  diagnosis: DiagnoseCropDiseaseOutput,
  farmerName: string,
  imageData?: string
) {
  const pdf = new jsPDF();
  let yPos = 20;
  
  // Header with logo/title
  pdf.setFillColor(34, 139, 34);
  pdf.rect(0, 0, 210, 40, 'F');
  pdf.setFontSize(24);
  pdf.setTextColor(255, 255, 255);
  pdf.text('FARMINGO', 105, 20, { align: 'center' });
  pdf.setFontSize(14);
  pdf.text('Crop Disease Diagnosis Report', 105, 30, { align: 'center' });
  
  yPos = 50;
  
  // Report Information Box
  pdf.setDrawColor(200, 200, 200);
  pdf.setFillColor(245, 245, 245);
  pdf.roundedRect(15, yPos, 180, 25, 3, 3, 'FD');
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Report Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, yPos + 8);
  pdf.text(`Report Time: ${new Date().toLocaleTimeString('en-US')}`, 20, yPos + 15);
  pdf.text(`Farmer Name: ${farmerName}`, 20, yPos + 22);
  
  yPos += 35;
  
  // Disease Identification Section
  pdf.setFillColor(220, 20, 60);
  pdf.rect(15, yPos, 180, 8, 'F');
  pdf.setFontSize(14);
  pdf.setTextColor(255, 255, 255);
  pdf.text('DISEASE IDENTIFICATION', 20, yPos + 6);
  yPos += 15;
  
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  pdf.setFont(undefined, 'bold');
  pdf.text('Disease Name:', 20, yPos);
  pdf.setFont(undefined, 'normal');
  pdf.text(diagnosis.diseaseName, 60, yPos);
  yPos += 7;
  
  pdf.setFont(undefined, 'bold');
  pdf.text('Severity Level:', 20, yPos);
  pdf.setFont(undefined, 'normal');
  pdf.text(diagnosis.affectedSeverity, 60, yPos);
  yPos += 7;
  
  pdf.setFont(undefined, 'bold');
  pdf.text('AI Confidence:', 20, yPos);
  pdf.setFont(undefined, 'normal');
  pdf.text(`${(diagnosis.confidence * 100).toFixed(1)}%`, 60, yPos);
  yPos += 7;
  
  pdf.setFont(undefined, 'bold');
  pdf.text('Model Used:', 20, yPos);
  pdf.setFont(undefined, 'normal');
  pdf.text(diagnosis.modelUsed || 'ResNet AI', 60, yPos);
  yPos += 7;
  
  if (diagnosis.cause) {
    pdf.setFont(undefined, 'bold');
    pdf.text('Cause:', 20, yPos);
    pdf.setFont(undefined, 'normal');
    const causeLines = pdf.splitTextToSize(diagnosis.cause, 130);
    pdf.text(causeLines, 60, yPos);
    yPos += causeLines.length * 5 + 2;
  }
  
  yPos += 5;
  
  // Weather Conditions Section
  if (diagnosis.weatherConditions) {
    pdf.setFillColor(255, 165, 0);
    pdf.rect(15, yPos, 180, 8, 'F');
    pdf.setFontSize(12);
    pdf.setTextColor(255, 255, 255);
    pdf.text('FAVORABLE WEATHER CONDITIONS', 20, yPos + 6);
    yPos += 15;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const weatherLines = pdf.splitTextToSize(diagnosis.weatherConditions, 170);
    pdf.text(weatherLines, 20, yPos);
    yPos += weatherLines.length * 5 + 10;
  }
  
  // Symptoms Section
  if (diagnosis.symptoms) {
    pdf.setFillColor(255, 140, 0);
    pdf.rect(15, yPos, 180, 8, 'F');
    pdf.setFontSize(12);
    pdf.setTextColor(255, 255, 255);
    pdf.text('SYMPTOMS', 20, yPos + 6);
    yPos += 15;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const symptomLines = pdf.splitTextToSize(diagnosis.symptoms, 170);
    pdf.text(symptomLines, 20, yPos);
    yPos += symptomLines.length * 5 + 10;
  }
  
  // Check if new page needed
  if (yPos > 240) {
    pdf.addPage();
    yPos = 20;
  }
  
  // Immediate Treatment Section
  pdf.setFillColor(220, 20, 60);
  pdf.rect(15, yPos, 180, 8, 'F');
  pdf.setFontSize(12);
  pdf.setTextColor(255, 255, 255);
  pdf.text('IMMEDIATE TREATMENT STEPS', 20, yPos + 6);
  yPos += 15;
  
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  const immediateLines = pdf.splitTextToSize(diagnosis.immediateSteps, 170);
  pdf.text(immediateLines, 20, yPos);
  yPos += immediateLines.length * 5 + 10;
  
  // Organic Treatment Section
  if (diagnosis.organicTreatment) {
    if (yPos > 240) {
      pdf.addPage();
      yPos = 20;
    }
    
    pdf.setFillColor(34, 139, 34);
    pdf.rect(15, yPos, 180, 8, 'F');
    pdf.setFontSize(12);
    pdf.setTextColor(255, 255, 255);
    pdf.text('ORGANIC TREATMENT OPTIONS', 20, yPos + 6);
    yPos += 15;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const organicLines = pdf.splitTextToSize(diagnosis.organicTreatment, 170);
    pdf.text(organicLines, 20, yPos);
    yPos += organicLines.length * 5 + 10;
  }
  
  // Chemical Treatment Section
  if (diagnosis.chemicalTreatment) {
    if (yPos > 240) {
      pdf.addPage();
      yPos = 20;
    }
    
    pdf.setFillColor(70, 130, 180);
    pdf.rect(15, yPos, 180, 8, 'F');
    pdf.setFontSize(12);
    pdf.setTextColor(255, 255, 255);
    pdf.text('CHEMICAL TREATMENT & PESTICIDES', 20, yPos + 6);
    yPos += 15;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const chemicalLines = pdf.splitTextToSize(diagnosis.chemicalTreatment, 170);
    pdf.text(chemicalLines, 20, yPos);
    yPos += chemicalLines.length * 5 + 10;
  }
  
  // Follow-up Care Section
  if (yPos > 240) {
    pdf.addPage();
    yPos = 20;
  }
  
  pdf.setFillColor(30, 144, 255);
  pdf.rect(15, yPos, 180, 8, 'F');
  pdf.setFontSize(12);
  pdf.setTextColor(255, 255, 255);
  pdf.text('FOLLOW-UP CARE', 20, yPos + 6);
  yPos += 15;
  
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  const followUpLines = pdf.splitTextToSize(diagnosis.followUpSteps, 170);
  pdf.text(followUpLines, 20, yPos);
  yPos += followUpLines.length * 5 + 10;
  
  // Preventive Measures Section
  if (diagnosis.preventiveMeasures) {
    if (yPos > 240) {
      pdf.addPage();
      yPos = 20;
    }
    
    pdf.setFillColor(138, 43, 226);
    pdf.rect(15, yPos, 180, 8, 'F');
    pdf.setFontSize(12);
    pdf.setTextColor(255, 255, 255);
    pdf.text('PREVENTIVE MEASURES', 20, yPos + 6);
    yPos += 15;
    
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    const preventiveLines = pdf.splitTextToSize(diagnosis.preventiveMeasures, 170);
    pdf.text(preventiveLines, 20, yPos);
    yPos += preventiveLines.length * 5 + 10;
  }
  
  // Additional Resources
  if (yPos > 240) {
    pdf.addPage();
    yPos = 20;
  }
  
  pdf.setFillColor(100, 100, 100);
  pdf.rect(15, yPos, 180, 8, 'F');
  pdf.setFontSize(12);
  pdf.setTextColor(255, 255, 255);
  pdf.text('ADDITIONAL RESOURCES', 20, yPos + 6);
  yPos += 15;
  
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  pdf.text('• Consult local agricultural extension services for region-specific advice', 20, yPos);
  yPos += 6;
  pdf.text('• Join Farmingo community to connect with other farmers', 20, yPos);
  yPos += 6;
  pdf.text('• For severe cases, contact a certified agricultural expert', 20, yPos);
  yPos += 6;
  pdf.text('• Keep records of treatments applied and their effectiveness', 20, yPos);
  
  // Footer on all pages
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(
      'Generated by Farmingo AI | For educational purposes | Consult experts for severe cases',
      105,
      285,
      { align: 'center' }
    );
    pdf.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
  }
  
  return pdf;
}