import jsPDF from 'jspdf';
import type { DiagnoseCropDiseaseOutput } from '@/ai/flows/crop-disease-diagnosis';

export function generateDiagnosisReport(
  diagnosis: DiagnoseCropDiseaseOutput,
  farmerName: string,
  imageData?: string
) {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(20);
  pdf.setTextColor(34, 139, 34);
  pdf.text('FARMINGO - Crop Disease Diagnosis Report', 20, 30);
  
  // Date and farmer info
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Date: ${new Date().toLocaleDateString()}`, 20, 50);
  pdf.text(`Farmer: ${farmerName}`, 20, 60);
  
  // Disease Information
  pdf.setFontSize(16);
  pdf.setTextColor(220, 20, 60);
  pdf.text('DISEASE DETECTED', 20, 80);
  
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Disease: ${diagnosis.diseaseName}`, 20, 95);
  pdf.text(`Severity: ${diagnosis.affectedSeverity}`, 20, 105);
  pdf.text(`AI Confidence: ${(diagnosis.confidence * 100).toFixed(1)}%`, 20, 115);
  pdf.text(`Model Used: ${diagnosis.modelUsed || 'ResNet AI'}`, 20, 125);
  
  // Immediate Treatment
  pdf.setFontSize(16);
  pdf.setTextColor(220, 20, 60);
  pdf.text('IMMEDIATE TREATMENT', 20, 145);
  
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  const immediateLines = pdf.splitTextToSize(diagnosis.immediateSteps, 170);
  pdf.text(immediateLines, 20, 160);
  
  // Follow-up Care
  const followUpY = 160 + (immediateLines.length * 5) + 15;
  pdf.setFontSize(16);
  pdf.setTextColor(30, 144, 255);
  pdf.text('FOLLOW-UP CARE', 20, followUpY);
  
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  const followUpLines = pdf.splitTextToSize(diagnosis.followUpSteps, 170);
  pdf.text(followUpLines, 20, followUpY + 15);
  
  // Additional Information
  const additionalY = followUpY + 15 + (followUpLines.length * 5) + 20;
  pdf.setFontSize(16);
  pdf.setTextColor(34, 139, 34);
  pdf.text('ADDITIONAL INFORMATION', 20, additionalY);
  
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  
  // General disease info
  const diseaseInfo = [
    'PREVENTION TIPS:',
    '• Maintain proper crop spacing for air circulation',
    '• Regular monitoring and early detection',
    '• Use disease-resistant crop varieties when available',
    '• Proper irrigation management',
    '• Clean farming tools between uses',
    '',
    'WHEN TO SEEK HELP:',
    '• If symptoms worsen after treatment',
    '• If disease spreads to other plants',
    '• For severe infestations requiring professional intervention',
    '',
    'COMMUNITY RESOURCES:',
    `• Visit: ${diagnosis.communityPostsLink}`,
    '• Connect with local agricultural extension services',
    '• Join farmer support groups in your area'
  ];
  
  let currentY = additionalY + 15;
  diseaseInfo.forEach(line => {
    if (line.startsWith('•') || line.startsWith('PREVENTION') || line.startsWith('WHEN') || line.startsWith('COMMUNITY')) {
      pdf.setFontSize(10);
      if (line.includes(':')) {
        pdf.setTextColor(34, 139, 34);
      } else {
        pdf.setTextColor(0, 0, 0);
      }
    }
    pdf.text(line, 20, currentY);
    currentY += 5;
  });
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by Farmingo AI - For educational purposes. Consult agricultural experts for severe cases.', 20, 280);
  
  return pdf;
}